//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipments()
        {
            this.Feedbacks = new HashSet<Feedbacks>();
            this.MaintenanceLogs = new HashSet<MaintenanceLogs>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int EquipmentID { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public string Name { get; set; }
        public int QuantityAvailable { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<System.DateTime> ShelfLife { get; set; }
        public Nullable<bool> IsReserved { get; set; }
    
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedbacks> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceLogs> MaintenanceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservations> Reservations { get; set; }
        public override string ToString()
        {
            return Name; // Возвращаем название оборудования для отображения в ComboBox
        }
    }
}
