//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int FeedbackID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comments { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipments Equipments { get; set; }
    }
}
