//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderClientView
    {
        public int OrderID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientFullName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string Status { get; set; }
    }
}
