//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime RentalStartDate { get; set; }
        public System.DateTime RentalEndDate { get; set; }
        public decimal PricePerDay { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Equipments Equipments { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
