//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Equipments
    {
        public int EquipmentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public string EquipmentType { get; set; }
        public int QuantityAvailable { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<System.DateTime> ShelfLife { get; set; }
        public Nullable<bool> IsReserved { get; set; }
    }
}
